title: "Meddlesome Podcast"
description: "Meddlesome Podcast. Short, sharp stories about the real work of running a small business — told by two operators who’ve lived it. No jargon. No theory. Just meddling."
markdown: kramdown

theme: minima

paginate: 6
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
