title: "Meddlesome"
description: "Stories of meddling by two professional meddelers" 
markdown: kramdown

theme: minima

url: "https://meddlesomepodcast.com"
baseurl: ""


collections:
  transcripts:
    output: true
    permalink: /transcripts/:name/
    markdown: true

paginate: 6
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

header_pages:
  - resources.md
  - subscribe.md 
  - about.md 